<?php
/*+**********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 ************************************************************************************/
$languageStrings = array(
	'SINGLE_Calendar'              => 'Compito'                     , 
	'LBL_ADD_TASK'                 => 'Aggiungi compito'            , 
	'LBL_ADD_EVENT'                => 'Aggiungi Evento'             , 
	'LBL_RECORDS_LIST'             => 'Vista per Lista'             , 
	'LBL_EVENTS'                   => 'Eventi'                      , 
	'LBL_TODOS'                    => 'Compiti'                     , 
	'LBL_CALENDAR_SETTINGS'        => 'Impostazioni calendario'     ,
	'LBL_CALENDAR_SHARING'         => 'Condivisione calendario'     , 
	'LBL_DEFAULT_EVENT_DURATION'   => 'Durata predefinita eventi'   , 
	'LBL_CALL'                     => 'Chiamata'                    , 
	'LBL_OTHER_EVENTS'             => 'Altri eventi'                , 
	'LBL_MINUTES'                  => 'Minuti'                      , 
	'LBL_SELECT_USERS'             => 'Seleziona utente'            , 
	'LBL_TASK_INFORMATION'         => 'Informazione Compito'        , 
	'Subject'                      => 'Soggetto'                    , 
	'Start Date & Time'            => 'Orario e data inizio'        , 
	'Activity Type'                => 'Tipo Attività'               , 
	'Send Notification'            => 'Manda Notifica'              , 
	'Location'                     => 'Luogo'                       , 
	'End Date & Time'              => 'Data e Ora Fine'             , 
	'LBL_ACTIVITY_TYPES'           => 'Tipologia attività'          , 
	'LBL_CONTACTS_SUPPORT_END_DATE' => 'Data Fine Supporto'         , 
	'LBL_CONTACTS_BIRTH_DAY'       => 'Data di nascita'             , 
	'LBL_ADDED_CALENDARS'          => 'Calendari aggiunti'          , 
	'Call'                         => 'Chiamata'                    , 
	'Meeting'                      => 'Riunione'                    , 
	'Task'                         => 'Compito'                     , 
	'Planned'                      => 'Pianificato'                 , 
	'Completed'                    => 'Completato'                  , 
	'Pending Input'                => 'In Attesa di Input'          , 
	'Not Started'                  => 'Non Iniziato'                , 
	'Deferred'                     => 'Posticipato'                 , 
	'Medium'                       => 'Medio'                       , 
	'LBL_CHANGE_OWNER'             => 'Cambia Proprietario'         , 
	'LBL_EVENT'                    => 'Evento'                      , 
	'LBL_TASK'                     => 'Compito'                     , 
	'LBL_CALENDAR_VIEW'            => 'Vista calendario'            , 
	'LBL_SHARED_CALENDAR'          => 'Calendario condiviso'        , 
	'LBL_DAY0'                     => 'Domenica'                    , 
	'LBL_DAY1'                     => 'Lunedì'                      , 
	'LBL_DAY2'                     => 'Martedì'                     , 
	'LBL_DAY3'                     => 'Mercoledì'                   , 
	'LBL_DAY4'                     => 'Giovedì'                     , 
	'LBL_DAY5'                     => 'Venerdì'                     , 
	'LBL_DAY6'                     => 'Sabato'                      , 
	'first'                        => 'Primo'                       , 
	'last'                         => 'Ultimo'                      , 
	'LBL_DAY_OF_THE_MONTH'         => 'giorno del mese'             , 
	'LBL_ON'                       => 'di'                          , 
	'Daily'                        => 'Giorno(i)'                   , 
	'Weekly'                       => 'Settimana(e)'                , 
	'Monthly'                      => 'Mese(i)'                     , 
	'Yearly'                       => 'Anno'                        , 
);
$jsLanguageStrings = array(
	'LBL_ADD_EVENT_TASK'           => 'Aggiungi evento / Compito'   , 
	'JS_TASK_IS_SUCCESSFULLY_ADDED_TO_YOUR_CALENDAR' => 'Il compito è stato aggiunto al calendario', 
	'LBL_SYNC_BUTTON'              => 'Sincronizza ora'             , 
	'LBL_SYNCRONIZING'             => 'Sto sincronizzando...'       , 
	'LBL_NOT_SYNCRONIZED'          => 'Non hai ancora sincronizzato', 
	'LBL_FIELD_MAPPING'            => 'Mappatura campi'             , 
	'LBL_CANT_SELECT_CONTACT_FROM_LEADS' => 'Impossibile selezionare Contatti correlati per i Leads', 
	
	//Calendar view label translation
	'LBL_MONTH' => 'Mese',
	'LBL_TODAY' => 'Oggi',
	'LBL_DAY' => 'Giorno',
	'LBL_WEEK' => 'Settimana',
	
	'LBL_SUNDAY' => 'Domenica',
	'LBL_MONDAY' => 'Lunedì',
	'LBL_TUESDAY' => 'Martedì',
	'LBL_WEDNESDAY' => 'Mercoledì',
	'LBL_THURSDAY' => 'Giovedì',
	'LBL_FRIDAY' => 'Venerdì',
	'LBL_SATURDAY' => 'Sabato',
	
	'LBL_SUN' => 'Dom',
	'LBL_MON' => 'Lun',
	'LBL_TUE' => 'Mar',
	'LBL_WED' => 'Mer',
	'LBL_THU' => 'Gio',
	'LBL_FRI' => 'Ven',
	'LBL_SAT' => 'Sab',
	
	'LBL_JANUARY' => 'Gennaio',
	'LBL_FEBRUARY' => 'Febbraio',
	'LBL_MARCH' => 'Marzo',
	'LBL_APRIL' => 'Aprile',
	'LBL_MAY' => 'Maggio',
	'LBL_JUNE' => 'giugno',
	'LBL_JULY' => 'Luglio',
	'LBL_AUGUST' => 'Agosto',
	'LBL_SEPTEMBER' => 'Settembre',
	'LBL_OCTOBER' => 'Ottobre',
	'LBL_NOVEMBER' => 'Novembre',
	'LBL_DECEMBER' => 'Dicembre',
	
	'LBL_JAN' => 'Grn',
	'LBL_FEB' => 'Feb',
	'LBL_MAR' => 'Mar',
	'LBL_APR' => 'Apr',
	'LBL_MAY' => 'Mag',
	'LBL_JUN' => 'Giu',
	'LBL_JUL' => 'Lug',
	'LBL_AUG' => 'Ago',
	'LBL_SEP' => 'Set',
	'LBL_OCT' => 'Ott',
	'LBL_NOV' => 'Nov',
	'LBL_DEC' => 'Dic',
	
	'LBL_ALL_DAY' => 'Tutti i giorni',
	//End
);
